name: belajar_dart_packages
description: A starting point for Dart libraries or applications.
version: 1.5.0
homepage: https://www.iqbalsuwandi20.com
repository: https://github.com/iqbalsuwandi20/belajar-dart-packages

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
